version: "3"
services:
  mariadb:
    image: mariadb:10
    container_name: "AppDB"
    restart: always
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1235
    volumes:
    - mysql:/var/lib/mysql
volumes:
  mysql: ~

